image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Ansible + Docker
    init: |
      sudo apt-get update
      sudo apt-get install -y ansible python3-pip docker.io
      python3 -m pip install --user docker
      ansible-galaxy collection install community.docker
      sudo service docker start
      bash scripts/start_lab.sh
    command: |
      echo "Ready. Try: make ping   or   make play"
