image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Ansible
    init: |
      sudo apt update && sudo apt install -y ansible docker.io
      sudo service docker start
      docker run -d --name web1 ubuntu:20.04 sleep infinity
      docker run -d --name web2 ubuntu:20.04 sleep infinity
    command: |
      echo "Welcome to your Ansible Gitpod lab!"
